#!/usr/bin/env bash

die() {
  echo "[-] Error: ${1}." >&2
  exit 1
}
log() {
  echo "[#] ${1}."
}

WIREGUARD_CONFIGS_DIR="/etc/wireguard"
read -p "[?] Generate wireguard interfaces for azirevpn ? [y/N]: " GENERATE
GENERATE="${GENERATE:-'N'}"
log "> ${GENERATE}"
if [[ "${GENERATE}" != 'y' ]]; then
  log "Skipping interfaces generation" && exit 0
else
  BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  cd "${BASEDIR}" || die "cd ${BASEDIR}"
  #./_install || die "couldn't generate configurations"
  log "wireguard interfaces successfully generated"
fi

CONFIGS="$(fd -t f -e conf --changed-within 10min "azirevpn" "${WIREGUARD_CONFIGS_DIR}" -x echo {/})"
[[ -z "${CONFIGS}" ]] && log "No new interface to import" && exit 0
CONNECTIONS="$(nmcli -g name c show | rg azirevpn)"
ACTIVE_CONNECTION="$(nmcli -g UUID c show --active | rg azirevpn)"
log "Importing new interfaces to Network Manager"
if [[ -n "${ACTIVE_CONNECTION}" ]]; then
  log "Disconnecting \"${ACTIVE_CONNECTION}\""
  nmcli c down "${ACTIVE_CONNECTION}"
  nmcli networking off
fi
for CONFIG in ${CONFIGS}
do
  CONFIG_NAME="$(basename ${CONFIG} .conf)"
  for CONNECTION in ${CONNECTIONS}
  do
    if [[ "${CONNECTION}" == "${CONFIG_NAME}" ]]; then
      nmcli c delete "${CONFIG_NAME}"
      break
    fi
  done
  log "Importing ${CONFIG_NAME}"
  sudo nmcli c import type wireguard file "${WIREGUARD_CONFIGS_DIR}/${CONFIG}"
  nmcli c down "${CONFIG_NAME}"
  nmcli c modify "${CONFIG_NAME}" autoconnect no
done
if [[ -n "${ACTIVE_CONNECTION}" ]]; then
  nmcli networking on
  log "Reconnecting \"${ACTIVE_CONNECTION}\""
  nmcli c up "${ACTIVE_CONNECTION}"
fi
log "Done importing interfaces"
