#!/usr/bin/env bash

die() {
  echo "Error: $1." >&2
  exit 1
}

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}"

CONFIG_DIR="configs"
CONFIG="${1}"
CONFIG_NAME="$(./scripts/getconfigname ${CONFIG})"
[[ -z "${CONFIG_NAME}" ]] && die "config \"${CONFIG}\" not supported"
shift

set -e

DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_DIR}/${CONFIG_NAME}" "${@}"
