#!/usr/bin/env bash

die() {
  echo "Error: $1." >&2
  exit 1
}

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}"

CONFIG_DIR="configs"
CONFIG="${1}"
CACHED_CONFIG="${BASEDIR}/${CONFIG_DIR}/.cached-config"
USE_CACHED=0
if [[ -z "${CONFIG}" ]]; then
  if [[ -f "${CACHED_CONFIG}" ]]; then
    CONFIG="$(head -n 1 < "${CACHED_CONFIG}")"
    USE_CACHED=1
  else
    die "config must be specified at least once"
  fi
fi
[[ ${USE_CACHED} -eq 0 ]] && printf "${CONFIG}" > "${CACHED_CONFIG}"
shift

set -e

DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
