#!/usr/bin/env bash
I1="${1}"
I2="${2}"
I3="${3}"
C1="${4}"
C2="${5}"
C3="${6}"

if [[ "$(nmcli networking connectivity)" == "full" ]]; then
  CONNECTIONS="$(nmcli -g NAME,TYPE,ACTIVE connection show)"
  ACTIVE="$(rg '.+:wireguard:yes$' <<<"${CONNECTIONS}")"
  if [[ -n "${ACTIVE}" ]]; then
    if [[ -n "$(rg '^azirevpn' <<< ${ACTIVE})" ]]; then
      NAME="$(perl -ne '/^azirevpn-(.+?):/ && print $1' <<<"${ACTIVE}")"
    else
      NAME="$(perl -ne '/^(.+?):/ && print $1' <<<"${ACTIVE}")"
    fi
    echo "%{F${C2}}${I1}%{F-} %{F${C1}}${NAME}%{F-}"
  else
    echo "%{F${C3}}${I2}%{F-}"
  fi
else
  echo "%{F${C3}}${I3}%{F-}"
fi
