#!/usr/bin/env bash

. "${XDG_CACHE_HOME}/wal/colors.sh"

dunstrc='[global]
    monitor = 0
    follow = mouse
    geometry = "250x60-0+70"
    indicate_hidden = yes
    shrink = no
    transparency = 20
    notification_height = 0
    separator_height = 2
    padding = 6
    horizontal_padding = 6
    frame_width = 2
    frame_color = "#aaaaaa"
    separator_color = frame
    sort = yes
    idle_threshold = 120
    font = Hack 10
    line_height = 0
    markup = full
    format = "<b>%s</b>\n%b"
    alignment = center
    show_age_threshold = 60
    word_wrap = yes
    ellipsize = middle
    ignore_newline = no
    stack_duplicates = true
    hide_duplicate_count = false
    show_indicators = yes
    icon_position = off
    max_icon_size = 32
    icon_path = /usr/share/icons/gnome/16x16/status/:/usr/share/icons/gnome/16x16/devices/
    sticky_history = yes
    history_length = 20
    dmenu = /usr/bin/dmenu -p dunst:
    browser = /usr/bin/firefox -new-tab
    always_run_script = true
    title = Dunst
    class = Dunst
    startup_notification = false
    force_xinerama = false
    [experimental]
    per_monitor_dpi = false

[shortcuts]
    close = ctrl+space
    close_all = ctrl+shift+space
    history = ctrl+grave
    context = ctrl+shift+period

[urgency_low]
    background = '"\"${color0:-#FFFFFF}\""'
    foreground = '"\"${color8:-#000000}\""'
    timeout = 4

[urgency_normal]
    background = '"\"${color0:-#FFFFFF}\""'
    foreground = '"\"${color15:-#000000}\""'
    timeout = 6

[urgency_critical]
    background = '"\"${color0:-#FFFFFF}\""'
    foreground = '"\"${color15:-#000000}\""'
    frame_color = '"\"${color13:-#FF0000}\""'
    timeout = 0'

printf "$dunstrc" > "${XDG_CONFIG_HOME}/dunst/dunstrc" && exit 0
