#!/usr/bin/env bash

die() {
  echo "[-] Error: ${1}." >&2
  exit 1
}
log() {
  echo "[#] ${1}."
}

CONFIG_FILE="/etc/X11/xorg.conf.d/50-mouse-acceleration.conf"
[[ -f "${CONFIG_FILE}" ]] && log "xorg mouse config already exists" && exit 0
PARENT="$(dirname ${CONFIG_FILE})"
[[ ! -d "${PARENT}" ]] && die "Couldn't find directory \"${PARENT}\""
cat <<EOF | sudo tee "${CONFIG_FILE}"
Section "InputClass"
        Identifier "My Mouse"
        Driver "libinput"
        MatchIsPointer "yes"
        Option "AccelProfile" "flat"
        Option "AccelSpeed" "0"
EndSection
EOF
log "xorg mouse config copied"
