#!/bin/sh
# Selection=true

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        echo "sourcing ${f}..."
        [ -x "$f" ] && . "$f"
        echo "sourced ${f} with ${?}" >> /tmp/emptty_log
    done
    unset f
fi

Environment=xorg
LoginShell=/bin/zsh --login

exec dbus-launch i3
