#!/usr/bin/env bash
VIDEO="${1}"
if [[ -z "${VIDEO}" ]]; then
  read -p "[?] Video path: " VIDEO
fi
read -p "[?] Add subtitles [Y/n]: " SUB
SUB=${SUB:-Y}
if [[ "${SUB}" = "Y" ]] || [[ "${SUB}" = "y" ]]; then
  SUBLIST=""
  SUBTITLES_DIR="/storage/subtitles"
  if [[ ! -d "${SUBTITLES_DIR}" ]]; then
    echo "[-] Couldn't find subtitles location, skipping selection"
  else
    while [[ "${SUB}" = "Y" ]] || [[ "${SUB}" = "y" ]]; do
      FILE="$(fd -t f -a -E "*orig*" -e srt -e idx -e sub . "${SUBTITLES_DIR}" \
        | fzf --prompt="Subtitle: ")"
      if [[ -n "${FILE}" ]]; then
        if [[ -n "${SUBLIST}" ]]; then
          SUBLIST="${SUBLIST}:${FILE}"
        else
          SUBLIST="${FILE}"
        fi
        echo "[+] Added \"$(basename "${FILE}")\""
      else
        echo "[-] Subtitle selection aborted, continuing"
        break
      fi
      read -p "[?] Add more subtitles [y/N]: " SUB
      SUB=${SUB:-N}
    done
  fi
fi
echo "[#] Playing \"$(basename "${VIDEO}")\""
if [[ -n "${SUBLIST}" ]]; then
  mpv "${VIDEO}" --sub-files="${SUBLIST}"
else
  mpv "${VIDEO}"
fi
