#!/usr/bin/env bash
ACTION="$(printf "copy\nshow\nedit" \
  | fzf --prompt="Action: ")"
[[ -z "$ACTION" ]] && exit 0
STORE_PATH="$HOME/.password-store/"
FILE="$(fd -t f . $STORE_PATH \
  | sed "s/\.gpg$//" \
  | sed "s/^${STORE_PATH//\//\\\/}//" \
  | fzf --prompt="File: ")"
[[ -z "$FILE" ]] && exit 0
case "$ACTION" in
  "copy")
    pass -c "$FILE"
    ;;
  "show")
    pass show "$FILE"
    ;;
  "edit")
    pass edit "$FILE"
    ;;
  *)
    exit 0
    ;;
esac
