#!/usr/bin/env bash
CONNECTIONS="$(nmcli -g name,type,active connection show)"
ACTIVE="$(perl -nle '/(.+):wireguard:yes$/ && print $1' <<<"${CONNECTIONS}")"
PEERS="$(perl -nle '/(.+):wireguard:(no|yes)$/ && print $1' <<<"${CONNECTIONS}")"
if [[ -n "${ACTIVE}" ]]; then
  PEERS="$(printf "${PEERS}\nNone")"
fi
PEER=$(fzf --prompt="Peer: " <<<"${PEERS}")
if [[ -n ${PEER} ]]; then
  if [[ -n "${ACTIVE}" || ${PEER} == "None" ]]; then
    echo "[#] Closing ${ACTIVE}"
    if nmcli c down "${ACTIVE}"; then
      echo "[+] Closed ${ACTIVE}"
    else
      echo "[!] Couldn't close ${ACTIVE}"
    fi
  fi
  if [[ "${PEER}" != "None" ]]; then
    echo "[#] Opening ${PEER}"
    if nmcli c up "${PEER}"; then
      echo "[+] Opened ${PEER}"
    else
      echo "[!] Couldn't open ${PEER}"
    fi
  fi
fi
