- shell:
  -
    command: ./scripts/trizen/install
    stdin: true
    stdout: true
    stderr: true
    description: Install package manager

  -
    command: ./scripts/packages/install
    stdin: true
    stdout: true
    stderr: true
    description: Install some packages

  -
    command: ./scripts/i3-window-killer/install
    stdin: true
    stdout: true
    stderr: true
    description: Install i3-windows-killer
