- defaults:
    link:
      create: true
      relink: true

- shell:
  -
    stdin: true
    stdout: true
    stderr: true
    command: ./scripts/generate_files arc
    description: Pre-process files for "arcane" configuration

- create:
   - ~/.bin
   - ~/.cache/less

- link:
    ~/.config/broot/conf.hjson: .generated/.config/broot/conf.hjson
    ~/.config/fdfind/globalignore: .generated/.config/fdfind/globalignore
    ~/.config/git/config: .generated/.config/git/config
    ~/.config/i3/config: .generated/.config/i3/config
    ~/.config/i3/scripts/bar: .generated/.config/i3/scripts/bar
    ~/.config/i3/scripts/kill: .bin/i3-window-killer/target/release/i3-window-killer
    ~/.config/i3/scripts/lock: .generated/.config/i3/scripts/lock
    ~/.config/i3/scripts/power: .generated/.config/i3/scripts/power
    ~/.config/i3/scripts/scratch_term: .generated/.config/i3/scripts/scratch_term
    ~/.config/i3/scripts/screenshot: .generated/.config/i3/scripts/screenshot
    ~/.config/mpv/mpv.conf: .generated/.config/mpv/mpv.conf
    ~/.config/nvim/init.vim: .generated/.config/nvim/init.vim
    ~/.config/oh-my-zsh/custom/plugins/asdf/asdf.plugin.zsh: .generated/.config/oh-my-zsh/custom/plugins/asdf/asdf.plugin.zsh
    ~/.config/oh-my-zsh/custom/themes/bureau.zsh-theme: .generated/.config/oh-my-zsh/custom/themes/bureau.zsh-theme
    ~/.config/picom/picom.conf: .generated/.config/picom/picom.conf
    ~/.config/polybar/base: .generated/.config/polybar/base
    ~/.config/polybar/scripts/bluetooth: .generated/.config/polybar/scripts/bluetooth
    ~/.config/polybar/scripts/hostname: .generated/.config/polybar/scripts/hostname
    ~/.config/polybar/scripts/uptime: .generated/.config/polybar/scripts/uptime
    ~/.config/polybar/scripts/vpn: .generated/.config/polybar/scripts/vpn
    ~/.config/rofi/config.rasi: .generated/.config/rofi/config.rasi
    ~/.config/rofi/kill.config.rasi: .generated/.config/rofi/kill.config.rasi
    ~/.config/rofi/kill.template.rasi: .generated/.config/rofi/kill.template.rasi
    ~/.config/wal/scripts/dunst: .generated/.config/wal/scripts/dunst
    ~/.config/wal/scripts/lock: .generated/.config/wal/scripts/lock
    ~/.config/wal/scripts/st: .generated/.config/wal/scripts/st
    ~/.config/wal/templates/colors.Xresources: .generated/.config/wal/templates/colors.Xresources
    ~/.config/wal/templates/polybar.config: .generated/.config/wal/templates/polybar.config
    ~/.config/wal/templates/rofi.base.rasi: .generated/.config/wal/templates/rofi.base.rasi
    ~/.config/wal/templates/rofi.kill.rasi: .generated/.config/wal/templates/rofi.kill.rasi
    ~/.config/wal/wal-set: .generated/.config/wal/wal-set
    ~/.scripts/myjail: .generated/.scripts/myjail
    ~/.scripts/mympv: .generated/.scripts/mympv
    ~/.scripts/mypass: .generated/.scripts/mypass
    ~/.scripts/myplug: .generated/.scripts/myplug
    ~/.scripts/mypwgen: .generated/.scripts/mypwgen
    ~/.scripts/myvpn: .generated/.scripts/myvpn
    ~/.scripts/myvpn-ns: .generated/.scripts/myvpn-ns
    ~/.scripts/mywal: .generated/.scripts/mywal
    ~/.scripts/p41: .generated/.scripts/p41
    ~/.xprofile: .generated/.xprofile
    ~/.zshenv: .generated/.zshenv
    ~/.zshrc: .generated/.zshrc

- clean:
    ~/.config:
      recursive: true

- shell:
  -
    command: ./scripts/trizen/install
    stdin: true
    stdout: true
    stderr: true
    description: Install package manager trizen

  -
    command: ./scripts/packages/install
    stdin: true
    stdout: true
    stderr: true
    description: Install base packages

  -
    command: ./scripts/i3-window-killer/install
    stdin: true
    stdout: true
    stderr: true
    description: Install i3 script i3-windows-killer

  -
    command: ./scripts/oh-my-zsh/install
    stdin: true
    stdout: true
    stderr: true
    description: Install zsh shell plugin manager oh-my-zsh

  -
    command: ./scripts/azirevpn/install
    stdin: true
    stdout: true
    stderr: true
    description: Configure azirevpn wireguard interfaces
