#!/usr/bin/env bash

die() {
  echo "Error: $1." >&2
  exit 1
}

command -v gpp 2>&1 > /dev/null || die "gpp not installed"

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}/../" || die "cd ${BASEDIR}"

CONFIG="${1}"
./scripts/getconfigname ${CONFIG} || die "config \"${CONFIG}\" not supported"

DOTFILES_DIR="dotfiles"
PROCESSED_DIR=".generated"
while read -r FILE
do
  PARENT="$(dirname ${FILE})"
  FILENAME="$(basename ${FILE})"
  mkdir -p "${PROCESSED_DIR}${PARENT#"${DOTFILES_DIR}"}"
  if [[ "${FILENAME}" == *.gpp ]]; then
    DEST="${PROCESSED_DIR}${PARENT#"${DOTFILES_DIR}"}/${FILENAME%.*}"
    gpp \
      -n -U "" "" "(" "," ")" "(" ")" "#" "" \
      -M "#" "\n" " " " " "\n" "(" ")" \
      -D__CFG="${CONFIG}" "${FILE}" > "${DEST}"
  else
    DEST="${PROCESSED_DIR}${PARENT#"${DOTFILES_DIR}"}/${FILENAME}"
    cp "${FILE}" "${DEST}"
  fi
  SHEBANG="$(head -n 1 ${DEST} | grep -E "^#\!/")"
  [[ ! -z "${SHEBANG}" ]] && chmod u+x "${DEST}"
done < <(fd -Ht f . "${DOTFILES_DIR}")
echo "[+] Done pre-processing dotfiles for \"${CONFIG}\""
