#!/usr/bin/env bash

c1=$(sed '16q;d' "$XDG_CACHE_HOME/wal/colors")
c2=$(sed '4q;d' "$XDG_CACHE_HOME/wal/colors")
i1="󰂯"
i2="󰂲"
bstatus="$(systemctl is-active bluetooth.service)"
if [[ $bstatus == "active" ]]; then
  echo "%{F$c1}$i1%{F-}"
else
  echo "%{F$c2}$i2%{F-}"
fi
