#!/usr/bin/env bash
ICONS=(󰼾 󰼂 󰻈 󰶵 󰶴 󰵹 󰴻 󰴂 󰮭 󰭡 󰪯 󰧵 󰧰 󰦫 󰥟 󰤇 󰤄 󰣚 󰣙 󰣎 󰣏 󰣐 󰣑 󰣇 󰢷 󰢠 󰢚 󰢛 󰢄 󰡶 󰡜 󰠥 󰠣 󰟠 󰜎 󰛅 󰚑 󰚌 󰚄 󰚀 󰙴 󰘗 󰘅 󰗢 󰗑 󰖝 󰖨 󰕈 󰕋 󰓥 󰒲 󰑮 󰑪 󰐼 󰍳 󰍲 󰌽 󰌟 󰌀 󰋇 󰊠 󰇷 󰇥 󰆚 󰆍 󰅲 󰃤 󰂧 󰁨 󰀜)
NUM=$(($(shuf -i 1-${#ICONS[@]} -n 1) - 1))
echo "${ICONS[$NUM]} $(uname -n)"
