#!/usr/bin/env bash
PROGRAM="${0##*/}"
GENERATED_LENGTH=20
CHARACTER_SET="[:punct:][:alnum:]"
CHARACTER_SET_NO_SYMBOL="[:alnum:]"
USAGE="Usage: $PROGRAM [--help, -h] [--clip,-c] [--no-symbol,-n] [pass-length]"
die() {
  echo "${1}"
  exit 1
}
[[ "$1" == "-h" || "$1" == "--help" ]] && echo "$USAGE" && exit 0

clip=0
characters="$CHARACTER_SET"
opts="$(getopt -o cn -l clip,no-symbol -n "$PROGRAM" -- "$@")"
err=$?
eval set -- "$opts"
while true; do case $1 in
        -c|--clip) clip=1; shift ;;
        -n|--no-symbol) characters="$CHARACTER_SET_NO_SYMBOL"; shift ;;
        --) shift; break ;;
esac done
[[ $err -ne 0 || $# -gt 2 ]] && die "$USAGE"
length="${1:-$GENERATED_LENGTH}"
read -r -n $length secret < <(LC_ALL=C tr -dc "$characters" < /dev/urandom)
[[ ${#secret} -eq $length ]] || die "Could not generate password from /dev/urandom."
[[ $clip == 1 ]] && echo -n "${secret}" | xclip -selection clipboard && exit 0
echo -n "${secret}" && exit 0
